name: main-merge-queue
on:
#  pull_request:
  push:
    branches:
      - 'mq-bot*'
  workflow_dispatch:
    inputs: {}
jobs:
  main:
    runs-on: "ubuntu-latest"
    steps:
      - name: merge-sleep
        shell: bash
        run: |
          sleep 60
          echo "testing error" >&2
          exit 1
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: merge-sleep
        shell: bash
        run: |
          sleep 10
